### ISSUE TITLE
Tensors on different devices

### ISSUE THREAD

**Issue by andreaspung** [JieyuZ2/wrench#4]
Hi, I am trying to run `run_meta_weight_net.py` but I am getting the following RuntimeError:

```
Traceback (most recent call last):
  File "run_meta_weight_net.py", line 67, in <module>
    device=device
  File "/gpfs/space/home/wrench/wrench/metalearning/meta_weight_net.py", line 166, in fit
    meta_loss = cross_entropy_with_probs(outputs, meta_target)
  File "/gpfs/space/home/wrench/wrench/utils.py", line 146, in cross_entropy_with_probs
    return F.cross_entropy(input, target.long(), weight=weight, reduction=reduction)
  File "/gpfs/space/home/.conda/envs/wrench2/lib/python3.6/site-packages/torch/nn/functional.py", line 2824, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument target in method wrapper_nll_loss_forward)
```

I have tried to reinstall my PyTorch but have had little success in getting it to work. Is this an environment error on my behalf or is it an actual bug in the code (one tensor being on the GPU and the other on the CPU when calculating cross-entropy loss)?

Thank you!

**Comment by JieyuZ2** [comment]
@andreaspung hey could you pull the latest version and see if the bugs are fixed?
